const wittyIntros = [
    "This vs. That: We'll help you decide, because we know you can't.",
    "This vs. That: Making your decisions for you since 2024.",
    "This vs. That: Finally, some data for your indecision.",
    "This vs. That: We do the agonizing research, so you don't have to.",
    "This vs. That: For when your brain has too many tabs open.",
    "This vs. That: Like a celebrity deathmatch, but for stuff.",
    "This vs. That: What do you mean they're both good?",
    "This vs. That: May the best gadget win.",
    "This vs. That: Our fight club, your shopping cart.",
    "This vs. That: The products have spoken. (Or, you know, we have.)",
    "This vs. That: The epic battle for your wallet.",
    "This vs. That: The ultimate showdown of stuff.",
    "This vs. That: A clash of titans in the palm of your hand.",
    "This vs. That: The final judgement for your purchases.",
    "This vs. That: Bringing peace to your inner conflict.",
    "This vs. That: Let's settle this.",
    "This vs. That: The case for and against.",
    "This vs. That: We have opinions.",
    "This vs. That: The definitive breakdown.",
    "This vs. That: For the picky shopper.",
    "This vs. That: Comparison shopping without the spreadsheet.",
    "This vs. That: Two products enter, one gets Prime.",
    "This vs. That: We split hairs so you don't split receipts.",
    "This vs. That: Specs, checks, and reality checks.",
    "This vs. That: Because 'it depends' isn't helpful.",
    "This vs. That: Side-by-side, minus the side-eye.",
    "This vs. That: Cutting through hype with a comparison knife.",
    "This vs. That: We read the manual. You're welcome.",
    "This vs. That: Less guesswork, more best work.",
    "This vs. That: Picks backed by data, not vibes.",
    "This vs. That: Shootout at the OK checkout.",
    "This vs. That: Your shortlist's judge and jury.",
    "This vs. That: Pros, cons, and plot twists.",
    "This vs. That: Because features ≠ benefits.",
    "This vs. That: We benchmark so you can binge-buy.",
    "This vs. That: Evidence, not influencer energy.",
    "This vs. That: We test, we stress, we confess.",
    "This vs. That: The tiebreaker you've been Googling for.",
    "This vs. That: Less FOMO, more ROI.",
    "This vs. That: Hard numbers, soft landing.",
    "This vs. That: Verdicts with receipts.",
    "This vs. That: Unbox the truth.",
    "This vs. That: The review that reviews reviews.",
    "This vs. That: Because your cart deserves closure.",
    "This vs. That: Small differences, big decisions.",
    "This vs. That: The algorithm's second opinion.",
    "This vs. That: We zoom in so you can zoom out.",
    "This vs. That: Specs speak louder than ads.",
    "This vs. That: We click so you don't have to.",
    "This vs. That: Sweat the details, skip the regret.",
    "This vs. That: Fewer tabs. Better buys.",
    "This vs. That: We do lab coats; you do add to cart.",
    "This vs. That: Battle-tested, budget-approved.",
    "This vs. That: Cutting through marketing, not corners.",
    "This vs. That: From spec sheet to street.",
    "This vs. That: The showdown your wallet asked for.",
    "This vs. That: Clarity at checkout.",
    "This vs. That: Built for the overthinker.",
    "This vs. That: Precision picks for picky people.",
    "This vs. That: Where hype meets evidence.",
    "This vs. That: Two contenders. One keeper.",
    "This vs. That: We separate need-to-have from nice-to-brag.",
    "This vs. That: Your decision, upgraded.",
    "This vs. That: The science of 'buy now'.",
    "This vs. That: We argue with ourselves so you don't.",
    "This vs. That: The final cut before the cut."
];

export const getRandomIntro = (): string => {
    const randomIndex = Math.floor(Math.random() * wittyIntros.length);
    return wittyIntros[randomIndex];
};
